### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xiaq** [anarazel/pg-vm-images#34]
Hi! I am trying to set up Cirrus CI tasks to run on OpenBSD and NetBSD and a series of links from https://github.com/cirruslabs/cirrus-ci-docs/issues/970 eventually led me here :)

I see you already have some pretty sophisticated Packer scripts for building those images, so I wish to be able to reuse them. But this repo doesn't seem to have a license file - do you mind clarifying which license the code is?

Also, it would be great if the OpenBSD and NetBSD images in `pg-ci-images` are public (Cirrus CI has the relevant gcloud command [documented](https://cirrus-ci.org/guide/custom-vms/#building-custom-image-for-compute-engine)) :) From my cursory read of the Packer scripts these images don't contain anything confidential, and AFAIK making images public won't incur any additional cost.

**Comment by nbyavuz** [comment]
Hi @xiaq! The images should be public, the [gcloud command](https://cirrus-ci.org/guide/custom-vms/#building-custom-image-for-compute-engine) you mentioned is [already run while creating the images](https://github.com/anarazel/pg-vm-images/blob/main/.cirrus.yml#L170).

**Comment by xiaq** [comment]
@nbyavuz Thanks! Indeed I can see the latest vanilla netbsd-vanilla image:

```
xiaqqaix@cloudshell:~$ gcloud compute images describe --project pg-ci-images pg-ci-netbsd-vanilla-2022-11-09t21-31-00
archiveSizeBytes: '379914048'
creationTimestamp: '2022-11-09T13:48:55.946-08:00'
diskSizeGb: '25'
family: pg-ci-netbsd-vanilla
id: '9066439252212031144'
kind: compute#image
labelFingerprint: 42WmSpB8rSM=
name: pg-ci-netbsd-vanilla-2022-11-09t21-31-00
rawDisk:
  containerType: TAR
  source: ''
selfLink: https://www.googleapis.com/compute/v1/projects/pg-ci-images/global/images/pg-ci-netbsd-vanilla-2022-11-09t21-31-00
sourceType: RAW
status: READY
storageLocations:
- us
```

Still, two requests :)

-   It'd still be useful to know what the code is licensed under :)

-   It's quite nontrivial to know the names of the images - I had to look at [Cirrus CI's logs](https://cirrus-ci.com/task/5836933568921600?logs=build_image#L1935) to track them down. Is it possible to allow all authenticated users to list images? There is a separate permission for that:

    ```
    xiaqqaix@cloudshell:~$ gcloud compute images list --project pg-ci-images --no-standard-images
    ERROR: (gcloud.compute.images.list) Some requests did not succeed:
     - Required 'compute.images.list' permission for 'projects/pg-ci-images'
    ```

    For reference I am already able to do this with another GCP project that contains FreeBSD images: `gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images`
